pipeline {
    agent any
    
    stages {
        stage('Download Data') {
            steps {
                script {
                    // Скачивание данных из GitHub
                    echo "----Download Data from GitHub (begin)-----"
                    git 'https://github.com/GeorgFeiler/MLOps.git'
                    echo "----Download Data from GitHub (end)-----"
                }
            }
        }

        stage('Run Scripts') {
            steps {
                script {
                    // Запуск скриптов
                    echo "----Run Scripts (begin)-----"
                    sh 'python3 /var/lib/jenkins/workspace/Jenkins Pipeline/lab1/data_creation.py'
                    sh 'python3 /var/lib/jenkins/workspace/Jenkins Pipeline/lab1/data_preprocessing.py'
                    sh 'python3 /var/lib/jenkins/workspace/Jenkins Pipeline/lab1/model_preparation.py'
                    sh 'python3 /var/lib/jenkins/workspace/Jenkins Pipeline/lab1/model_testing.py'
                    echo "----Run Scripts (end)-----"
                }
            }
        }
    }
}
